import type { CardDefinition } from "./types";

export const CARD_LIBRARY: CardDefinition[] = [
  {
    id: "basic-addition",
    name: "基础加法",
    description: "增加 2-6 分。",
    keywords: ["基础"],
    rarity: "common",
    levelRange: [1, 5],
    baseWeight: 6,
    effect: {
      type: "add",
      target: "self",
      minValue: 2,
      maxValue: 6,
    },
    tags: ["combo"],
  },
  {
    id: "precise-subtract",
    name: "精准扣减",
    description: "减少对手 1-4 分。",
    keywords: ["干扰", "护盾克制"],
    rarity: "common",
    levelRange: [2, 5],
    baseWeight: 4,
    effect: {
      type: "transfer",
      target: "opponent",
      minValue: 1,
      maxValue: 4,
    },
    tags: ["aggressive"],
  },
  {
    id: "risk-reset",
    name: "归零试胆",
    description: "将自身分数重置为 1，并获得 2 次额外抽牌机会。",
    keywords: ["风险", "额外抽牌"],
    rarity: "uncommon",
    levelRange: [1, 5],
    baseWeight: 2,
    effect: {
      type: "reset",
      target: "self",
      value: 1,
      notes: "gain-extra-draw-2",
    },
    tags: ["risk"],
  },
  {
    id: "power-double",
    name: "暴击倍增",
    description: "将当前分数乘以 2。",
    keywords: ["倍增", "高收益"],
    rarity: "uncommon",
    levelRange: [2, 5],
    baseWeight: 3,
    effect: {
      type: "multiply",
      target: "self",
      value: 2,
    },
    tags: ["multiplier"],
  },
  {
    id: "triple-charge",
    name: "三连击倒计时",
    description: "增加 4-8 分并获得 1 次额外抽牌机会。",
    keywords: ["加分", "额外抽牌", "连击"],
    rarity: "uncommon",
    levelRange: [3, 5],
    baseWeight: 2,
    effect: {
      type: "add",
      target: "self",
      minValue: 4,
      maxValue: 8,
      notes: "gain-extra-draw-1",
    },
    tags: ["combo"],
  },
  {
    id: "victory-shard",
    name: "命运碎片",
    description: "收集 3 枚立即获得整场胜利，可携带至下一层。",
    keywords: ["胜利碎片", "收藏"],
    rarity: "rare",
    levelRange: [1, 5],
    baseWeight: 1,
    maxCopies: 1,
    effect: {
      type: "victoryShard",
      target: "self",
      value: 1,
      carryOver: true,
    },
    tags: ["collectible"],
  },
  {
    id: "level-pass",
    name: "层级通行证",
    description: "判分时触发，将该层分数提升至至少 50。可留至下一层。",
    keywords: ["保底", "层级通行证"],
    rarity: "rare",
    levelRange: [2, 5],
    baseWeight: 1,
    effect: {
      type: "levelPass",
      target: "self",
      value: 50,
      carryOver: true,
    },
    tags: ["pass"],
  },
  {
    id: "hold-amplifier",
    name: "滞留增幅器",
    description: "若滞留位已有卡牌，则复制一份并立即结算其中一张。",
    keywords: ["滞留位", "复制"],
    rarity: "rare",
    levelRange: [3, 5],
    baseWeight: 1,
    effect: {
      type: "duplicate",
      target: "self",
    },
    tags: ["combo"],
  },
  {
    id: "merchant-token",
    name: "旅行商人推荐函",
    description: "下一次旅行商人阶段提供额外优惠并可免费获取一张卡。",
    keywords: ["商人", "优惠"],
    rarity: "legendary",
    levelRange: [2, 4],
    baseWeight: 0.3,
    effect: {
      type: "merchantToken",
      target: "self",
      value: 1,
      carryOver: true,
    },
    tags: ["merchant"],
  },
  {
    id: "counter-shield",
    name: "反制护盾",
    description: "获得 1 次护盾，可抵挡一次负向效果。",
    keywords: ["护盾", "防御"],
    rarity: "uncommon",
    levelRange: [1, 5],
    baseWeight: 2,
    effect: {
      type: "shield",
      target: "self",
      value: 1,
      carryOver: true,
    },
    tags: ["defense"],
  },
  {
    id: "wildcard-switch",
    name: "百变替换",
    description: "选择双方之一，将双方分数互换；若自身领先则无事发生。",
    keywords: ["翻盘", "交换分数"],
    rarity: "legendary",
    levelRange: [4, 5],
    baseWeight: 0.5,
    effect: {
      type: "wildcard",
      target: "both",
    },
    tags: ["swing"],
  },
  {
    id: "equilibrium-shift",
    name: "均衡摇摆",
    description: "在 -4 至 +5 的区间内随机调整自身分数。",
    keywords: ["基础", "随机"],
    rarity: "common",
    levelRange: [1, 5],
    baseWeight: 5,
    effect: {
      type: "add",
      target: "self",
      minValue: -4,
      maxValue: 5,
    },
    tags: ["math", "swing"],
  },
  {
    id: "basic-division",
    name: "基础除法",
    description: "将自身分数除以 2（向下取整）。",
    keywords: ["基础", "负面"],
    rarity: "common",
    levelRange: [1, 5],
    baseWeight: 3,
    effect: {
      type: "divide",
      target: "self",
      value: 2,
      script: "math.divide",
    },
    tags: ["math"],
  },
  {
    id: "power-surge",
    name: "平方奔涌",
    description: "将当前分数平方（上限 200）。",
    keywords: ["基础", "平方"],
    rarity: "rare",
    levelRange: [2, 5],
    baseWeight: 1.8,
    effect: {
      type: "script",
      target: "self",
      value: 2,
      script: "math.power",
      notes: "cap=200",
    },
    tags: ["math", "burst"],
  },
  {
    id: "basic-root",
    name: "基础开根",
    description: "将当前分数开平方取整。",
    keywords: ["基础", "负面"],
    rarity: "common",
    levelRange: [1, 5],
    baseWeight: 1.4,
    effect: {
      type: "script",
      target: "self",
      value: 0.5,
      script: "math.power",
    },
    tags: ["math", "control"],
  },
  {
    id: "scarlet-fragment",
    name: "赤红碎片",
    description: "失去 6 分，获得 1 枚赤红胜利碎片。",
    keywords: ["碎片", "收藏", "风险"],
    rarity: "rare",
    levelRange: [1, 5],
    baseWeight: 1,
    effect: {
      type: "victoryShard",
      target: "self",
      script: "shard.cost",
      value: 1,
      notes: "color=赤红|scorePenalty=6",
      carryOver: true,
    },
    tags: ["collectible", "shard"],
  },
  {
    id: "azure-fragment",
    name: "湛蓝碎片",
    description:
      "获取 1 枚湛蓝胜利碎片，但下一层抽牌次数 -1，开局额外失去 4 分。",
    keywords: ["碎片", "收藏", "代价"],
    rarity: "rare",
    levelRange: [2, 5],
    baseWeight: 0.9,
    effect: {
      type: "victoryShard",
      target: "self",
      script: "shard.cost",
      value: 1,
      notes: "color=湛蓝|nextDrawPenalty=1|startScorePenalty=4",
      carryOver: true,
    },
    tags: ["collectible", "shard"],
  },
  {
    id: "void-pact",
    name: "虚空盟约",
    description: "放弃本层余下的抽牌次数并失去 8 分，换取 1 枚虚空碎片。",
    keywords: ["碎片", "高风险", "抽牌"],
    rarity: "legendary",
    levelRange: [2, 5],
    baseWeight: 0.4,
    effect: {
      type: "script",
      target: "self",
      value: -1,
      script: "shard.tradeDraw",
      notes: "color=虚空|scorePenalty=8|shards=1",
      carryOver: true,
    },
    tags: ["collectible", "risk"],
  },
  {
    id: "threshold-ritual",
    name: "门槛仪式",
    description: "当自身分数不超过 10 时，获得 1 枚碎片；否则承受 4 分惩罚。",
    keywords: ["碎片", "条件"],
    rarity: "uncommon",
    levelRange: [1, 5],
    baseWeight: 1.5,
    effect: {
      type: "script",
      target: "self",
      value: 10,
      script: "shard.threshold",
      notes: "scorePenalty=4|shards=1|color=仪式",
      carryOver: true,
    },
    tags: ["collectible", "risk"],
  },
  {
    id: "zero-crash",
    name: "零点坠落",
    description: "将对手的分数直接清零，若被护盾阻挡则无效。",
    keywords: ["干扰", "归零"],
    rarity: "rare",
    levelRange: [3, 5],
    baseWeight: 1.2,
    effect: {
      type: "script",
      target: "opponent",
      value: 0,
      script: "score.set",
    },
    tags: ["aggressive", "disrupt"],
  },
  {
    id: "chaos-inversion",
    name: "混沌反转",
    description: "令对手分数取反，可被护盾抵挡。",
    keywords: ["干扰", "反转"],
    rarity: "legendary",
    levelRange: [4, 5],
    baseWeight: 0.6,
    effect: {
      type: "script",
      target: "opponent",
      script: "score.invert",
    },
    tags: ["aggressive", "disrupt"],
  },
  {
    id: "leech-siphon",
    name: "虹吸寄生",
    description: "窃取对手 30% 的当前分数，护盾可抵挡本次窃取。",
    keywords: ["干扰", "吸取"],
    rarity: "uncommon",
    levelRange: [2, 5],
    baseWeight: 2.2,
    effect: {
      type: "script",
      target: "opponent",
      value: 30,
      script: "score.percentTransfer",
    },
    tags: ["aggressive"],
  },
  {
    id: "draw-lockdown",
    name: "抽牌锁定",
    description: "使对手下一层的基础抽牌次数 -1。",
    keywords: ["干扰", "抽牌限制"],
    rarity: "uncommon",
    levelRange: [2, 5],
    baseWeight: 2,
    effect: {
      type: "script",
      target: "opponent",
      value: 1,
      script: "debuff.drawPenalty",
    },
    tags: ["aggressive", "control"],
  },
  {
    id: "hold-resonance",
    name: "滞留共振",
    description: "根据当前滞留位数量，每张提供 +3 分的连击增幅。",
    keywords: ["滞留", "连击"],
    rarity: "common",
    levelRange: [2, 5],
    baseWeight: 3.5,
    effect: {
      type: "script",
      target: "self",
      value: 3,
      script: "hold.boost",
    },
    tags: ["combo"],
  },
  {
    id: "cascade-release",
    name: "滞留倾泻",
    description: "弃置全部滞留卡，每张获得 5 分。",
    keywords: ["滞留", "爆发"],
    rarity: "rare",
    levelRange: [3, 5],
    baseWeight: 1.2,
    effect: {
      type: "script",
      target: "self",
      value: 5,
      script: "hold.burn",
    },
    tags: ["combo", "burst"],
  },
  {
    id: "slot-expander",
    name: "滞留拓展",
    description: "本层起将滞留位上限提升 1（最高 4）。",
    keywords: ["滞留", "容量"],
    rarity: "uncommon",
    levelRange: [2, 5],
    baseWeight: 1.8,
    effect: {
      type: "script",
      target: "self",
      value: 1,
      script: "hold.expand",
      notes: "max=4",
    },
    tags: ["combo", "support"],
  },
  {
    id: "steady-ward",
    name: "稳固守卫",
    description: "将自身分数稳定在至少 12 点，并增强防线。",
    keywords: ["防御", "保底"],
    rarity: "common",
    levelRange: [1, 5],
    baseWeight: 3,
    effect: {
      type: "script",
      target: "self",
      value: 12,
      script: "defense.steadyBuffer",
    },
    tags: ["defense"],
  },
  {
    id: "guardian-oath",
    name: "守护誓约",
    description: "将自身分数提升至对手当前分数的一半（向上取整）。",
    keywords: ["防御", "反击"],
    rarity: "legendary",
    levelRange: [3, 5],
    baseWeight: 0.7,
    effect: {
      type: "script",
      target: "self",
      script: "score.floorHalf",
    },
    tags: ["defense", "swing"],
  },
  {
    id: "resource-harvest",
    name: "资源收割",
    description: "放弃余下抽牌次数并按剩余次数的平方获取分数。",
    keywords: ["资源", "抽牌"],
    rarity: "rare",
    levelRange: [2, 5],
    baseWeight: 1.6,
    effect: {
      type: "script",
      target: "self",
      script: "resource.drawToScore",
      notes: "mode=quadratic",
    },
    tags: ["resource"],
  },
  {
    id: "echo-retrieval",
    name: "回声检索",
    description: "从弃牌堆顶回收 1 张卡至滞留位，若滞留已满则失败。",
    keywords: ["资源", "循环", "滞留"],
    rarity: "uncommon",
    levelRange: [2, 5],
    baseWeight: 2,
    effect: {
      type: "script",
      target: "self",
      script: "resource.recoverDiscard",
    },
    tags: ["resource", "combo"],
  },
];
